services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: friendly-fyzio-app
    env_file: .env.prod
    depends_on:
      - redis
    volumes:
      - type: bind
        source: /volumes/friendly-fyzio-app/storage/app
        target: /var/www/storage/app
      - type: bind
        source: /volumes/friendly-fyzio-app/storage/logs
        target: /var/www/storage/logs
      - type: tmpfs
        target: /var/www/bootstrap/cache
      - type: tmpfs
        target: /var/www/storage/framework/cache
      - type: tmpfs
        target: /var/www/storage/framework/sessions
      - type: tmpfs
        target: /var/www/storage/framework/views
    labels:
      - "traefik.enable=true"
      # HTTP router - redirects to HTTPS
      - "traefik.http.routers.friendly-fyzio-app.rule=Host(`friendly-fyzio.com`)"
      - "traefik.http.routers.friendly-fyzio-app.entrypoints=web"
      - "traefik.http.routers.friendly-fyzio-app.middlewares=friendly-fyzio-app-redirect"
      # HTTPS router
      - "traefik.http.routers.friendly-fyzio-app-secure.rule=Host(`friendly-fyzio.com`)"
      - "traefik.http.routers.friendly-fyzio-app-secure.entrypoints=websecure"
      - "traefik.http.routers.friendly-fyzio-app-secure.tls.certresolver=myresolver"
      # Service
      - "traefik.http.services.friendly-fyzio-app.loadbalancer.server.port=8000"
      # Redirect middleware
      - "traefik.http.middlewares.friendly-fyzio-app-redirect.redirectscheme.scheme=https"
      - "traefik.docker.network=web"
    networks:
      - web
      - database
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: friendly-fyzio-app-worker
    env_file: .env.prod
    depends_on:
      - redis
    command: sh -c "php artisan schedule:work & php artisan queue:work --sleep=3 --tries=3 --max-time=3600"
    volumes:
      - type: bind
        source: /volumes/friendly-fyzio-app/storage/app
        target: /var/www/storage/app
      - type: bind
        source: /volumes/friendly-fyzio-app/storage/logs
        target: /var/www/storage/logs
      - type: tmpfs
        target: /var/www/bootstrap/cache
      - type: tmpfs
        target: /var/www/storage/framework/cache
      - type: tmpfs
        target: /var/www/storage/framework/sessions
      - type: tmpfs
        target: /var/www/storage/framework/views
    networks:
      - database
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: friendly-fyzio-redis
    volumes:
      - friendly-fyzio-redis:/data
    networks:
      - database
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    restart: unless-stopped

networks:
  web:
    external: true
  database:
    external: true

volumes:
  friendly-fyzio-redis:
    driver: local
