<?php

namespace App\Filament\Clusters\Kurzy\Resources\CourseLessons\RelationManagers;

use App\Filament\Support\Actions\MoveClientIntoLessonAction;
use App\Filament\Support\Actions\ToggleLessonAttendanceAction;
use App\Models\CourseLesson;
use App\Models\LessonAttendance;
use App\Support\Enrollments\LessonRoster;
use BackedEnum;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Columns\ToggleColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

/**
 * Presence list for a single lesson, shown as a section on the lesson detail
 * page. One row per enrolled client, generated by the enrollment/lesson lifecycle
 * ({@see LessonRoster}). Staff can additionally pull a
 * client in from another série via the header "Přesunout klienta do lekce"
 * override ({@see MoveClientIntoLessonAction}).
 *
 * The middle column reads the lesson's tense. Before it happens the question is
 * "Zúčastní se?" — answering no frees the spot for somebody else, so it asks
 * first ({@see ToggleLessonAttendanceAction}). Once the lesson is over the
 * question is simply who turned up, ticked off as it goes.
 */
class AttendancesRelationManager extends RelationManager
{
    protected static string $relationship = 'attendances';

    protected static ?string $title = 'Docházka';

    protected static string|BackedEnum|null $icon = Heroicon::OutlinedCheckCircle;

    public function isReadOnly(): bool
    {
        return false;
    }

    private function lessonHasHappened(): bool
    {
        $lesson = $this->getOwnerRecord();

        return $lesson instanceof CourseLesson && $lesson->startsAt()->isPast();
    }

    public function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn (Builder $query): Builder => $query->with('enrollment.client'))
            ->defaultSort('created_at')
            ->headerActions([
                MoveClientIntoLessonAction::make(),
            ])
            ->columns([
                TextColumn::make('enrollment.client.name')
                    ->label('Klient')
                    ->searchable()
                    ->placeholder('—'),
                $this->lessonHasHappened()
                    ? ToggleColumn::make('attended')
                        ->label('Účast')
                    : IconColumn::make('will_attend')
                        ->label('Zúčastní se?')
                        ->boolean()
                        ->state(fn (LessonAttendance $record): bool => $record->cancelled_at === null)
                        ->tooltip(fn (LessonAttendance $record): string => $record->cancelled_at === null
                            ? 'Počítáme s ním — kliknutím ho odhlásíte'
                            : 'Odhlášen, místo je volné — kliknutím ho vrátíte')
                        ->action(ToggleLessonAttendanceAction::make()),
                TextColumn::make('cancelled_at')
                    ->label('Zrušeno')
                    ->dateTime('d.m.Y H:i')
                    ->placeholder('—')
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->emptyStateHeading('Zatím žádná docházka')
            ->emptyStateDescription('Účast se objeví po přihlášení klientů do série.');
    }
}
