<?php

namespace App\Filament\Clusters\Kurzy\Resources\CourseLessons\RelationManagers;

use App\Filament\Support\Actions\MoveClientIntoLessonAction;
use BackedEnum;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Columns\ToggleColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

/**
 * Presence list for a single lesson, shown as a section on the lesson detail
 * page. One row per enrolled client with an inline "attended" toggle; regular
 * rows are generated by the enrollment/lesson lifecycle. Staff can additionally
 * pull a client in from another série via the header "Přesunout klienta do lekce"
 * override ({@see MoveClientIntoLessonAction}).
 */
class AttendancesRelationManager extends RelationManager
{
    protected static string $relationship = 'attendances';

    protected static ?string $title = 'Docházka';

    protected static string|BackedEnum|null $icon = Heroicon::OutlinedCheckCircle;

    public function isReadOnly(): bool
    {
        return false;
    }

    public function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn (Builder $query): Builder => $query->with('enrollment.client'))
            ->defaultSort('created_at')
            ->headerActions([
                MoveClientIntoLessonAction::make(),
            ])
            ->columns([
                TextColumn::make('enrollment.client.name')
                    ->label('Klient')
                    ->searchable()
                    ->placeholder('—'),
                ToggleColumn::make('attended')
                    ->label('Účast'),
                TextColumn::make('cancelled_at')
                    ->label('Zrušeno')
                    ->dateTime('d.m.Y H:i')
                    ->placeholder('—')
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->emptyStateHeading('Zatím žádná docházka')
            ->emptyStateDescription('Účast se objeví po přihlášení klientů do série.');
    }
}
